Challenge1/Models/Contact.cs
namespace Challenge1.Models
{
    public class Contact
    {
        public int Id { get; private set; }
        public string FirstName { get; private set; }
        public string LastName { get; private set; }
        public string SurName { get; private set; }
        public string PhoneNumber { get; private set; }
        public string Address { get; private set; }
        public string Description { get; private set; }

        private static int currentId;

        static Contact()
        {
            currentId = 0;
        }

        public static int GetId()
        {
            return currentId;
        }

        public Contact(string firstName, string lastName, string surName,
                       string phoneNumber, string address, string descrtiption)
        {
            Id = currentId;
            FirstName = firstName;
            LastName = lastName;
            SurName = surName;
            PhoneNumber = phoneNumber;
            Address = address;
            Description = descrtiption;
            currentId++;
        }

        public Contact(int id, string firstName, string lastName, string surName,
                        string phoneNumber, string address, string descrtiption)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            SurName = surName;
            PhoneNumber = phoneNumber;
            Address = address;
            Description = descrtiption;
        }
    }
}

Challenge1/Models/ContactRepository.cs
using System.Collections;

namespace Challenge1.Models
{
    public class ContactRepository : IEnumerable<Contact>
    {
        List<Contact> contacts;

        public ContactRepository(List<Contact> contactList) 
        {
            contacts = contactList;
        }

        public void AddContact(Contact contact)
        {
            contacts.Add(contact);
        }

        public IEnumerator<Contact> GetEnumerator()
        {
            return contacts.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public Contact this[int id]
        {
            get { return contacts[id]; }
        }
    }
}

Challenge1/Models/ContactRepositoryFabric.cs
using System.Collections.Generic;

namespace Challenge1.Models
{
    public static class ContactRepositoryFabric
    {
        public static ContactRepository GetContactRepository(int count)
        {
            List<Contact> list = new List<Contact>();
            for (int i = 0; i < count; i++)
            {
                Contact tempContact = new Contact($"Имя {i}", $"Фамилия {i}", $"Отчество {i}",
                    $"+790{i}56{i}5{i}{i}{i}", $"Адрес {i}", $"Описание {i}");
                list.Add(tempContact);
            }
            return new ContactRepository(list);
        }

        public static ContactRepository GetContactRepository(List<Contact> contacts)
        {
            return new ContactRepository(contacts);
        }
    }
}

Challenge1/Models/FileReader.cs
using System.Globalization;
using System.Security.Principal;
using System.Xml.Linq;

namespace Challenge1.Models
{
    public class FileReader
    {

        public static ContactRepository ReadContactsFromFile()
        {
            CheckFilesExist();

            List<Contact> contacts = new List<Contact>();

            XDocument xdoc = XDocument.Load("contacts.xml");
            foreach (XElement element in xdoc.Element("Contacts").Elements("Contact"))
            {
                XAttribute lastNameAttribute = element.Attribute("LastName");
                XAttribute firstNameAttribute = element.Attribute("FirstName");
                XAttribute surNameAttribute = element.Attribute("SurName");
                XElement idElement = element.Element("Id");
                XElement phoneNumberElement = element.Element("PhoneNumber"); 
                XElement addressElement = element.Element("Address");
                XElement decriptionElement = element.Element("Description");

                int currentId = int.Parse(idElement.Value);
                contacts.Add(new Contact(currentId, lastNameAttribute.Value, firstNameAttribute.Value, surNameAttribute.Value,
                    phoneNumberElement.Value, addressElement.Value, decriptionElement.Value));

            }
            return ContactRepositoryFabric.GetContactRepository(contacts);
        }

        private static void CheckFilesExist()
        {
            if (!File.Exists("contacts.xml"))
            {
                File.Create("contacts.xml").Close();
                ContactRepository contacts = ContactRepositoryFabric.GetContactRepository(10);
                FileSaver.SaveToFiles(contacts);
            }
        }
    }
}

Challenge1/Models/FileSaver.cs
using System.Xml.Linq;

namespace Challenge1.Models
{
    public class FileSaver
    {
        public static void SaveToFiles(ContactRepository clients)
        {
            List<Contact> contactList = clients.ToList();
            SaveToClientsFile(contactList);
        }

        private static void SaveToClientsFile(List<Contact> contactList)
        {
            XElement xContacts = new XElement("Contacts");
            for (int i = 0; i < contactList.Count; i++)
            {
                XElement contactElement = new XElement("Contact",
                        new XAttribute($"LastName", contactList[i].LastName),
                        new XAttribute($"FirstName", contactList[i].FirstName),
                        new XAttribute($"SurName", contactList[i].SurName),
                        new XElement("Id", contactList[i].Id),
                        new XElement("PhoneNumber", contactList[i].PhoneNumber),
                        new XElement("Address", contactList[i].Address),
                        new XElement("Description", contactList[i].Description));
                xContacts.Add(contactElement);
            }
            xContacts.Save("contacts.xml");
        }
    }
}

Challenge1/Controllers/PhoneBookController.cs
using Challenge1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Challenge1.Controllers
{
    public class PhoneBookController : Controller
    {
        ContactRepository contacts;

        public PhoneBookController()
        {
            contacts = FileReader.ReadContactsFromFile();
        }

        public IActionResult Index()
        {
            return View(contacts);
        }

        public IActionResult ContactPage(int id)
        {
            return View(contacts[id]);
        }
    }
}

Challenge1/Views/PhoneBook/ContactPage.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model Challenge1.Models.Contact
@{
    ViewData["Title"] = $"Контакт {Model.Id}" ;
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <h3>Контакст @Model.Id</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Фамилия</td>
            <td>Имя</td>
            <td>Отчество</td>
            <td>Номер телефона</td>
            <td>Адрес</td>
            <td>Описание</td>
            <td></td>
        </tr>
            <tr>
                <td>@Model.Id</td>
                <td>@Model.LastName</td>
                <td>@Model.FirstName</td>
                <td>@Model.SurName</td>
                <td>@Model.PhoneNumber</td>
                <td>@Model.Address</td>
                <td>@Model.Description</td>
            </tr>
    </table>
    <a asp-action="Index"><input type="button" value="Home"></a>
</body>
</html>

Challenge1/Views/PhoneBook/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<Challenge1.Models.Contact>
@{
    ViewData["Title"] = "Список контактов";
    Layout = null;
}
<!DOCTYPE html>
 
<html>
<head>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <h3>Контакты</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Фамилия</td>
            <td>Имя</td>
            <td>Отчество</td>
            <td></td>
        </tr>
        @foreach (var contact in Model)
            {
            <tr>
                <td><a asp-controller="PhoneBook" asp-action="ContactPage" asp-route-id="@contact.Id">@contact.Id</a></td>
                <td>@contact.LastName</td>
                <td>@contact.FirstName</td>
                <td>@contact.SurName</td>
            </tr>
        }
    </table>
</body>
</html>